[project]
name = "multi-diamond"
authors = ["Core Blockchain Team"]
description = "A decentralized multi-stakeholder project management platform"
telemetry = false
requirements = []
[contracts.multi-diamond-manager]
path = "contracts/multi-diamond-manager.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
